//! Generate a self-contained MkDocs project from an analysis snapshot.

use crate::model::{AnalysisResult, ModuleInfo};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const MARKER: &str = ".moduleloom-generated";
const GENERATED_HEADER: &str = "<!-- Generated by ModuleLoom. Edits will be replaced. -->\n\n";

pub fn generate(result: &AnalysisResult, output: &Path) -> Result<(), String> {
    generate_with_lang(result, output, "auto")
}

pub fn generate_with_lang(
    result: &AnalysisResult,
    output: &Path,
    lang: &str,
) -> Result<(), String> {
    let lang = resolve_lang(lang)?;
    let ja = lang == "ja";
    if output.exists() {
        if !output.is_dir() {
            return Err(format!("Output is not a directory: {}", output.display()));
        }
        let unmarked = fs::read_dir(output)
            .map_err(|error| error.to_string())?
            .next()
            .is_some()
            && !output.join(MARKER).exists();
        if unmarked {
            return Err(format!(
                "Output directory is not empty and was not generated by ModuleLoom: {}",
                output.display()
            ));
        }
    }
    fs::create_dir_all(output.join("docs/modules")).map_err(|error| error.to_string())?;
    fs::create_dir_all(output.join("docs/javascripts")).map_err(|error| error.to_string())?;

    let mut modules: Vec<&ModuleInfo> = result.modules.iter().collect();
    modules.sort_by(|a, b| a.id.cmp(&b.id).then(a.relative_path.cmp(&b.relative_path)));
    let pages: BTreeMap<&str, String> = modules
        .iter()
        .enumerate()
        .map(|(index, module)| (module.id.as_str(), format!("modules/{index:04}.md")))
        .collect();

    let old_pages = fs::read_to_string(output.join(MARKER)).unwrap_or_default();
    for old_page in old_pages.lines() {
        if !old_page.starts_with("modules/")
            || old_page.contains("..")
            || !old_page.ends_with(".md")
        {
            continue;
        }
        if !pages.values().any(|page| page == old_page) {
            let path = output.join("docs").join(old_page);
            if fs::read_to_string(&path).is_ok_and(|content| content.starts_with(GENERATED_HEADER))
            {
                fs::remove_file(path).map_err(|error| error.to_string())?;
            }
        }
    }

    let project_name = result
        .root_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("Python project");
    let mut config = format!(
        "site_name: {}\ntheme:\n  name: material\n  language: {}\nuse_directory_urls: false\nmarkdown_extensions:\n  - pymdownx.superfences:\n      custom_fences:\n        - name: mermaid\n          class: mermaid\n          format: !!python/name:pymdownx.superfences.fence_code_format\nextra_javascript:\n  - javascripts/mermaid.mjs\nnav:\n  - {}: index.md\n",
        serde_json::to_string(project_name).map_err(|error| error.to_string())?,
        lang,
        if ja { "概要" } else { "Overview" }
    );
    config.push_str(&format!("\n# Documentation language: {lang}\n"));
    if !modules.is_empty() {
        config.push_str(if ja {
            "  - モジュール:\n"
        } else {
            "  - Modules:\n"
        });
    }
    for module in &modules {
        config.push_str(&format!(
            "      - {}: {}\n",
            serde_json::to_string(&module.id).map_err(|error| error.to_string())?,
            pages[module.id.as_str()]
        ));
    }
    write(output.join("mkdocs.yml"), &config)?;
    write(
        output.join("docs/javascripts/mermaid.mjs"),
        "import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';\nmermaid.initialize({ startOnLoad: false, securityLevel: 'loose' });\nwindow.mermaid = mermaid;\n",
    )?;

    let all_ids: BTreeSet<&str> = modules.iter().map(|module| module.id.as_str()).collect();
    let mut index = format!(
        "{GENERATED_HEADER}# {project_name}\n\n## {}\n\n",
        if ja {
            "モジュール依存関係"
        } else {
            "Module dependency graph"
        }
    );
    index.push_str(&diagram(result, &all_ids, &pages, false, ja));
    index.push_str(if ja {
        "\n## モジュール\n\n"
    } else {
        "\n## Modules\n\n"
    });
    for module in &modules {
        index.push_str(&format!(
            "- [{}]({}) — {}\n",
            module.id,
            pages[module.id.as_str()],
            summary(module.docstring.as_deref(), ja)
        ));
    }
    if modules.is_empty() {
        index.push_str(if ja {
            "Pythonモジュールが見つかりませんでした。\n"
        } else {
            "No Python modules were found.\n"
        });
    }
    write(output.join("docs/index.md"), &index)?;

    for module in &modules {
        let connected: BTreeSet<&str> = result
            .edges
            .iter()
            .filter(|edge| edge.source == module.id || edge.target == module.id)
            .flat_map(|edge| [edge.source.as_str(), edge.target.as_str()])
            .chain(std::iter::once(module.id.as_str()))
            .filter(|id| pages.contains_key(id))
            .collect();
        let mut page = format!("{GENERATED_HEADER}# {}\n\n", module.id);
        page.push_str(&diagram(result, &connected, &pages, true, ja));
        page.push_str(if ja {
            "\n[← 全体図](../index.md)\n\n"
        } else {
            "\n[← Overall graph](../index.md)\n\n"
        });
        page.push_str(if ja {
            "## 説明\n\n"
        } else {
            "## Description\n\n"
        });
        page.push_str(
            &module
                .docstring
                .as_deref()
                .filter(|text| !text.trim().is_empty())
                .map(clean_docstring)
                .unwrap_or_else(|| {
                    if ja {
                        "モジュールの説明はありません。".into()
                    } else {
                        "No module docstring.".into()
                    }
                }),
        );
        page.push_str("\n\n");

        let mut documented = Vec::new();
        for class in &module.classes {
            {
                let docstring = class
                    .docstring
                    .as_deref()
                    .filter(|text| !text.trim().is_empty());
                documented.push((
                    class.line,
                    format!(
                        "### class {}\n\n{}\n\n",
                        class.name,
                        docstring.map(clean_docstring).unwrap_or_else(|| if ja {
                            "説明はありません。".into()
                        } else {
                            "No description.".into()
                        })
                    ),
                ));
            }
        }
        for function in &module.functions {
            {
                let docstring = function
                    .docstring
                    .as_deref()
                    .filter(|text| !text.trim().is_empty());
                let parent = function
                    .parent_class_line
                    .and_then(|line| module.classes.iter().find(|class| class.line == line));
                let name = parent.map_or_else(
                    || function.name.clone(),
                    |class| format!("{}.{}", class.name, function.name),
                );
                documented.push((
                    function.line,
                    format!(
                        "### {}\n\n{}\n\n",
                        name,
                        docstring.map(clean_docstring).unwrap_or_else(|| if ja {
                            "説明はありません。".into()
                        } else {
                            "No description.".into()
                        })
                    ),
                ));
            }
        }
        documented.sort_by_key(|(line, _)| *line);
        for (_, section) in documented {
            page.push_str(&section);
        }
        write(output.join("docs").join(&pages[module.id.as_str()]), &page)?;
    }
    let manifest = pages.values().cloned().collect::<Vec<_>>().join("\n");
    write(output.join(MARKER), &manifest)?;
    Ok(())
}

fn write(path: PathBuf, content: &str) -> Result<(), String> {
    fs::write(&path, content).map_err(|error| format!("{}: {error}", path.display()))
}

fn summary(docstring: Option<&str>, ja: bool) -> String {
    let cleaned = docstring.map(clean_docstring);
    let first = cleaned
        .as_deref()
        .and_then(|text| text.lines().find(|line| !line.trim().is_empty()))
        .unwrap_or(if ja { "説明なし" } else { "No docstring" })
        .trim();
    first.replace(['\n', '\r', '[', ']'], " ")
}

fn resolve_lang(lang: &str) -> Result<String, String> {
    let auto = lang.eq_ignore_ascii_case("auto");
    let value = if auto {
        std::env::var("LC_ALL")
            .ok()
            .filter(|s| !s.is_empty())
            .or_else(|| std::env::var("LC_MESSAGES").ok().filter(|s| !s.is_empty()))
            .or_else(|| std::env::var("LANG").ok())
            .unwrap_or_else(|| "en".into())
    } else {
        lang.to_string()
    };
    let primary = value
        .split(['-', '_', '.'])
        .next()
        .unwrap_or("en")
        .to_ascii_lowercase();
    match primary.as_str() {
        "ja" => Ok("ja".into()),
        "en" => Ok("en".into()),
        _ if auto => Ok("en".into()),
        _ => Err(format!(
            "Unsupported documentation language '{lang}'. Use auto, ja, or en."
        )),
    }
}

fn clean_docstring(text: &str) -> String {
    let lines: Vec<&str> = text.lines().collect();
    let indent = lines
        .iter()
        .skip(1)
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.len() - line.trim_start().len())
        .min()
        .unwrap_or(0);
    let mut cleaned = Vec::new();
    if let Some(first) = lines.first() {
        cleaned.push(first.trim().to_string());
    }
    for line in lines.iter().skip(1) {
        cleaned.push(line.get(indent..).unwrap_or("").trim_end().to_string());
    }
    cleaned.join("\n").trim().to_string()
}

fn diagram(
    result: &AnalysisResult,
    ids: &BTreeSet<&str>,
    pages: &BTreeMap<&str, String>,
    from_module: bool,
    ja: bool,
) -> String {
    let nodes: BTreeMap<&str, String> = ids
        .iter()
        .enumerate()
        .map(|(index, id)| (*id, format!("n{index}")))
        .collect();
    let mut output = String::from("```mermaid\nflowchart LR\n");
    if ids.is_empty() {
        output.push_str(if ja {
            "  empty[\"モジュールなし\"]\n"
        } else {
            "  empty[\"No modules\"]\n"
        });
    }
    for (id, node) in &nodes {
        let label = serde_json::to_string(id).unwrap_or_default();
        output.push_str(&format!("  {node}[{label}]\n"));
    }
    let edges: BTreeSet<(&str, &str)> = result
        .edges
        .iter()
        .filter(|edge| {
            nodes.contains_key(edge.source.as_str()) && nodes.contains_key(edge.target.as_str())
        })
        .map(|edge| (edge.source.as_str(), edge.target.as_str()))
        .collect();
    for (source, target) in edges {
        output.push_str(&format!("  {} --> {}\n", nodes[source], nodes[target]));
    }
    for (id, node) in &nodes {
        let path = &pages[id];
        let href = if from_module {
            format!(
                "{}.html",
                path.trim_start_matches("modules/").trim_end_matches(".md")
            )
        } else {
            format!("{}.html", path.trim_end_matches(".md"))
        };
        output.push_str(&format!(
            "  click {node} href {} {}\n",
            serde_json::to_string(&href).unwrap_or_default(),
            serde_json::to_string(if ja {
                "モジュールページを開く"
            } else {
                "Open module page"
            })
            .unwrap_or_default()
        ));
    }
    output.push_str("```\n");
    output
}

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::analyze_directory;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn generates_linked_diagrams_and_docstring_manual() {
        let project = tempdir().unwrap();
        fs::write(
            project.path().join("a.py"),
            "\"\"\"Module guide.\n    More details.\n    \"\"\"\nimport b\n\nclass Service:\n    \"\"\"Service guide.\"\"\"\n    def run(self):\n        \"\"\"Run guide.\"\"\"\n        pass\n",
        )
        .unwrap();
        fs::write(project.path().join("b.py"), "\"\"\"Second module.\"\"\"\n").unwrap();
        let result = analyze_directory(project.path()).unwrap();
        let output = tempdir().unwrap();
        generate(&result, output.path()).unwrap();

        let index = fs::read_to_string(output.path().join("docs/index.md")).unwrap();
        let page = fs::read_to_string(output.path().join("docs/modules/0000.md")).unwrap();
        assert!(index.contains("click n0 href \"modules/0000.html\""));
        assert!(index.contains("[a](modules/0000.md)"));
        assert!(page.find("```mermaid").unwrap() < page.find("## Description").unwrap());
        assert!(page.contains("Module guide."));
        assert!(page.contains("Module guide.\nMore details."));
        assert!(page.contains("Service guide."));
        assert!(page.contains("Run guide."));
        assert!(page.contains("click n1 href \"0001.html\""));
        assert!(page.contains("[← Overall graph](../index.md)"));

        fs::remove_file(project.path().join("b.py")).unwrap();
        let updated = analyze_directory(project.path()).unwrap();
        generate(&updated, output.path()).unwrap();
        assert!(!output.path().join("docs/modules/0001.md").exists());
    }
}
